name: flake-check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  pipeline:
    name: nix-check
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30

      - name: Check linting
        run: nix run .#statix check . -- --ignore hosts/*/hardware-configuration.nix

      - name: nix flake check
        run: nix flake check --print-build-logs --no-update-lock-file